# This Resource Definition of type "config" uses the Template Driver to provide configuration values
# to other Resource Definitions for accessing the AWS Project
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: wi-aws-app-config
entity:
  name: wi-aws-app-config
  type: config
  driver_type: humanitec/template
  # The identity used in this Cloud Account needs permission to manage
  # the kinds of cloud resources used in the example
  driver_account: YOURVALUE
  driver_inputs:
    values:
      templates:
        outputs: |
          region: YOURVALUE
  criteria:
    - class: default
      res_id: app-config
      env_type: development
      app_id: workload-identity-test-aws