# This Resource Definition uses the Template Driver to create a Kubernetes service account.
# Unlike IAM roles for service accounts, EKS Pod Identity doesn’t use an annotation on the service account
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: wi-aws-custom-service-account
entity:
  driver_type: humanitec/template
  name: wi-aws-custom-service-account
  type: k8s-service-account
  driver_inputs:
    values:
      res_id: ${context.res.id}
      templates:
        init: |
          res_id: {{ .driver.values.res_id }}
          {{- $res_name := index (splitList "." .driver.values.res_id) 1 }}
          name: {{ $res_name | toRawJson }}
        manifests: |
          service-account.yaml:
            location: namespace
            data:
              apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: {{ .init.name }}
                annotations:
                  hum-res: {{ .init.res_id }}
        outputs: |
          name: {{ .init.name }}
  # Co-provision an aws-role to represent this service account in IAM through workload identity
  # By specifying neither class nor ID, the co-provisioned aws-role will have the same class and ID as the present resource
  provision:
    aws-role:
      is_dependent: true
      match_dependents: true
  # Adjust matching criteria as required
  criteria:
  - app_id: workload-identity-test-aws