# This Resource Definition uses the Terraform Driver to create IAM policies for gcs resources of the class "read-only"
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: wi-aws-s3-aws-policy-read-only
entity:
  driver_type: humanitec/terraform
  name: wi-aws-s3-aws-policy-read-only
  type: aws-policy
  # Obtain the Cloud Account from a config resource
  driver_account: ${resources['config.default#app-config'].account}
  driver_inputs:
    values:
      variables:
        # Obtain the bucket name from the bucket resource this resource depends on
        s3_bucket_name: ${resources['s3.read-only'].outputs.name}
        # This resource selector traverses the Graph via s3 and workload to read the principal output from all k8s-service-account resources
        # TODO What do we need in the S3 case?
        # principals: 
      credentials_config:
        environment:
          AWS_ACCESS_KEY_ID: AccessKeyId
          AWS_SECRET_ACCESS_KEY: SecretAccessKey
          AWS_SESSION_TOKEN: SessionToken
      files:
        providers.tf: |
          terraform {
            required_providers {
              aws = {
                source  = "hashicorp/aws"
              }
            }
          }
        variables.tf: |
          variable "s3_bucket_name" {}
          # This variable is a set because a resource selector, which is used to retrieve it, always returns an array
          variable "principals" {
            type = set(string)
          }
        main.tf: |
          # Provider credentials are being injected through environment variables
          provider "aws" {
            default_tags {
              tags = {
                humanitec  = "true"
                hum-app    = var.app_id
                hum-env    = var.env_id
                hum-res    = replace(var.res_id, ".", "-")
                managed-by = "terraform"
              }
            }
          }
          # TODO - create Bucket policies here (loop!)
        outputs.tf: |
          # This output is for debugging and illustration purposes only
          output "principals" {
            value = join(",", var.principals)
          }   
  # Match the class that is used in the "provision" statement in the s3 Resource Definition
  criteria:
    - class: s3-read-only