# This Resource Definition of type "aws-role" uses the Terraform Driver to provision a bucket policy
# for an S3 buckets of access class "read-only"
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: wi-aws-s3-bucket-policy-read-only
entity:
  driver_type: humanitec/terraform
  name: wi-aws-s3-bucket-policy-read-only
  type: aws-policy
  driver_account: ${resources['config.default#app-config'].account}
  driver_inputs:
    values:
      append_logs_to_error: true
      variables:
        app_id: ${context.app.id}
        env_id: ${context.env.id}
        res_id: ${context.res.id}
        region: ${resources['config.default#app-config'].outputs.region}
        s3_bucket_arn: ${resources['s3.read-only'].outputs.arn}
        s3_bucket_name: ${resources['s3.read-only'].outputs.bucket}
        # This resource selector traverses the Graph via s3 and workload to read the "arn" output from all aws-role resources
        principals: ${resources['s3.read-only<workload>aws-role'].outputs.arn}
      credentials_config:
        environment:
          AWS_ACCESS_KEY_ID: AccessKeyId
          AWS_SECRET_ACCESS_KEY: SecretAccessKey
          AWS_SESSION_TOKEN: SessionToken
      files:
        providers.tf: | 
          terraform {
            required_providers {
              aws = {
                source  = "hashicorp/aws"
              }
            }
          }
        variables.tf: |
          variable "app_id" {}
          variable "env_id" {}
          variable "res_id" {}
          variable "region" {}
          variable "s3_bucket_arn" {}
          variable "s3_bucket_name" {}
          # This variable is a set because a resource selector, which is used to retrieve it, always returns an array
          variable "principals" {
            type = set(string)
          }
        main.tf: |
          # Provider credentials are being injected through environment variables
          provider "aws" {
            region = var.region
            default_tags {
              tags = {
                humanitec  = "true"
                hum-app    = var.app_id
                hum-env    = var.env_id
                hum-res    = replace(var.res_id, ".", "-")
                managed-by = "terraform"
              }
            }
          }
          resource "aws_s3_bucket_policy" "readonly_access" {
            bucket = var.s3_bucket_name
            policy = data.aws_iam_policy_document.bucket_readonly_access.json
          }
          data "aws_iam_policy_document" "bucket_readonly_access" {
            statement {
              # Enter each eligible role into the bucket policy
              dynamic "principals" {
                for_each = var.principals
                content {
                  type        = "AWS"
                  identifiers = ["$\{principals.value}"]
                }
              }
              actions = [
                "s3:GetObject",
                "s3:GetObjectVersion",
                "s3:ListBucket",
              ]
              resources = [
                var.s3_bucket_arn,
                "$\{var.s3_bucket_arn}/*",
              ]
            }
          }
        outputs.tf: |
          # No output "arn". A bucket policy does not have an ARN
          # This output is for debugging and illustration purposes only
          output "principals" {
            value = join(",", var.principals)
          } 
  # Match the class that is used in the "provision" statement in the Delegator s3 Resource Definition
  criteria:
  - class: s3-read-only