# This Resource Definition of type `s3` implements a "Delegator" resource for the class "admin"
# It uses the Template Driver to generate the corresponding IAM policy document
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: wi-aws-s3-delegator-admin
entity:
  driver_type: humanitec/template
  name: wi-aws-s3-delegator-admin
  type: s3
  driver_inputs:
    values:
      resClass: ${context.res.class}
      # Referencing the "concrete" Resource and passing through all of its outputs
      bucket_arn: ${resources['s3.concrete'].outputs.arn}
      bucket_name: ${resources['s3.concrete'].outputs.bucket}
      bucket_region: ${resources['s3.concrete'].outputs.region}
      # Collect the ARNs of all roles requiring the current access class on the S3 bucket
      principals: ${resources['s3.admin<workload>aws-role'].outputs.arn}
      templates:
        # The init template is used to prepare the IAM policy document content
        init: |
          iam_policy_document:
            Statement:
            - Sid: {{ .driver.values.resClass | quote }}
              Action:
              - "s3:*"
              Effect: "Allow"
              Principal:
                AWS:
                {{- range .driver.values.principals }}
                - {{ . | quote }}
                {{- end }}
              Resource:
              - "{{ .driver.values.bucket_arn }}"
              - "{{ .driver.values.bucket_arn }}/*"
        outputs: |
          arn: {{ .driver.values.bucket_arn | toRawJson }}
          bucket: {{ .driver.values.bucket_name | toRawJson }}
          region: {{ .driver.values.bucket_region | toRawJson }}
          principals: {{ .driver.values.principals | toRawJson }}
          iam_policy_document: {{ .init.iam_policy_document | toRawJson | quote }}
  provision:
   # Co-provision an IAM Policy resource
    aws-policy.s3:
      is_dependent: true
  # Adjust matching criteria as required, but must match class "admin"
  criteria:
  - class: admin
    app_id: workload-identity-test-aws