# This Resource Definition of type `s3` implements a "Delegator" resource for the class "read-only"
# It uses the Template Driver to generate the corresponding IAM policy document
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: wi-aws-s3-delegator-read-only
entity:
  driver_type: humanitec/echo
  name: wi-aws-s3-delegator-read-only
  type: s3
  driver_inputs:
    values:
      # Referencing the "concrete" Resource and passing through all of its outputs
      arn: ${resources['s3.concrete'].outputs.arn}
      name: ${resources['s3.concrete'].outputs.bucket}
      region: ${resources['s3.concrete'].outputs.region}
  # Adjust matching criteria as required, but must match class "read-only"
  criteria:
  - class: read-only
    app_id: workload-identity-test-aws