# This Resource Definition of type "config" uses the Echo Driver to provide configuration values
# to other Resource Definitions for accessing the Google Cloud Project
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: wi-gcp-app-config
entity:
  name: wi-gcp-app-config
  type: config
  driver_type: humanitec/echo
  driver_inputs:
    values:
      project_id: YOURVALUE
      region: YOURVALUE
  criteria:
    - class: default
      res_id: app-config
      env_type: development
      app_id: workload-identity-test-gcp