# This Resource Definition uses the Template Driver to create a Kubernetes service account.
# It pulls central configuration parameters from `config` Resources.
# It returns the "principal" string for the ServiceAccount to configure GKE workload identity.
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: wi-gcp-custom-service-account
entity:
  driver_type: humanitec/template
  name: wi-gcp-custom-service-account
  type: k8s-service-account
  driver_inputs:
    values:
      res_id: ${context.res.id}
      gke_project_id: ${resources['config.default#gke-config'].outputs.gke_project_id}
      gke_project_number: ${resources['config.default#gke-config'].outputs.gke_project_number}
      # Using the id `k8s-namespace`, this reference targets the existing, implicitly created namespace resource
      k8s_namespace: "${resources['k8s-namespace.default#k8s-namespace'].outputs.namespace}"
      templates:
        init: |
          res_id: {{ .driver.values.res_id }}
          {{- $res_name := index (splitList "." .driver.values.res_id) 1 }}
          name: {{ $res_name | toRawJson }}
          principal: principal://iam.googleapis.com/projects/{{ .driver.values.gke_project_number }}/locations/global/workloadIdentityPools/{{ .driver.values.gke_project_id }}.svc.id.goog/subject/ns/{{ .driver.values.k8s_namespace }}/sa/{{ $res_name }}
        manifests: |
          service-account.yaml:
            location: namespace
            data:
              apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: {{ .init.name }}
                annotations:
                  hum-res: {{ .init.res_id }}
        outputs: |
          name: {{ .init.name }}
          principal: {{ .init.principal }}
  # Adjust matching criteria as required
  criteria:
  - app_id: workload-identity-test-gcp