# This Resource Definition of type "config" uses the Echo Driver to provide configuration values
# to other Resource Definitions about the GKE cluster
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: wi-gcp-gke-config
entity:
  name: wi-gcp-gke-config
  type: config
  driver_type: humanitec/echo
  driver_inputs:
    values:
      gke_project_id: YOURVALUE
      # Keep the "" around the value of gke_project_number
      gke_project_number: "YOURVALUE"
  criteria:
    - class: default
      res_id: gke-config
      env_type: development
      app_id: workload-identity-test-gcp