# This Resource Definition of type "config" uses the Template Driver to provide configuration values
# to other Resource Definitions for accessing the GKE cluster
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: wi-gcp-gke-config
entity:
  name: wi-gcp-gke-config
  type: config
  driver_type: humanitec/template
  # The identity configured in this Cloud Account needs permission
  # to deploy Workloads to your GKE cluster
  driver_account: YOURACCOUNT
  driver_inputs:
    values:
      templates:
        outputs: |
          gke_project_id: YOURVALUE
          # Keep the "" around the value of gke_project_number
          gke_project_number: "YOURVALUE"
  criteria:
    - class: default
      res_id: gke-config
      env_type: development
      app_id: workload-identity-test-gcp