# This Resource Definition of type "config" uses the Template Driver to provide configuration values
# to other Resource Definitions for accessing the Azure subscription
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: wi-azure-app-config
entity:
  name: wi-azure-app-config
  type: config
  driver_type: humanitec/echo
  driver_inputs:
    values:
      subscription_id: YOURVALUE
      resource_group_name: YOURVALUE
      location: YOURVALUE
      aks_oidc_issuer_url: "YOURVALUE"
  criteria:
    - class: default
      res_id: app-config
      env_type: development
      app_id: workload-identity-test-azure