# This Resource Definition creates an Azure federated identity credential
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: wi-azure-federated-identity-credential
entity:
  driver_type: humanitec/opentofu-container-runner-builtin
  name: wi-azure-federated-identity-credential
  type: azure-federated-identity
  driver_inputs:
    values:
      files:
        input_vars.auto.tfvars.json: |
          {
            "azure_managed_identity_id" : "${resources['azure-managed-identity.@#@'].outputs.id}",
            "k8s-namespace"             : "${resources['k8s-namespace#k8s-namespace'].outputs.namespace}",
            "k8s-serviceaccount"        : "${resources['k8s-service-account.@#@'].outputs.name}",
            "aks_oidc_issuer_url"       : "${resources['config.default#app-config'].outputs.aks_oidc_issuer_url}",
            "humanitec_org_id"          : "${context.org.id}"
          }
        main.tf: |
          resource "azurerm_federated_identity_credential" "this" {
            name                      = "Pod-identity-for-$\{var.k8s-namespace}-$\{var.k8s-serviceaccount}"
            audience                  = ["api://AzureADTokenExchange"]
            issuer                    = var.aks_oidc_issuer_url
            user_assigned_identity_id = var.azure_managed_identity_id
            subject                   = "system:serviceaccount:$\{var.k8s-namespace}:$\{var.k8s-serviceaccount}"
          }
        outputs.tf: |
          output "id" {
            value = azurerm_federated_identity_credential.this.id
          }
        providers.tf: |
          terraform {
            required_providers {
              azurerm = {
                source  = "hashicorp/azurerm"
                version = ">=4.78.0"
              }
            }
          }
          provider "azurerm" {
            features {}
          }
        variables.tf: |
          variable "azure_managed_identity_id" {}
          variable "k8s-namespace" {}
          variable "k8s-serviceaccount" {}
          variable "aks_oidc_issuer_url" {}
          variable "humanitec_org_id" {}
      runner:
        variables:
          ARM_SUBSCRIPTION_ID: ${resources['config.default#app-config'].outputs.subscription_id}
          ARM_USE_CLI: '''false'''
          ARM_USE_AKS_WORKLOAD_IDENTITY: '''true'''
        # Setup for runner workload identity
        pod_template: |
          metadata:
            labels:
              azure.workload.identity/use: "true"
          spec:
            serviceAccountName: humanitec-runner
      # Using the default TF backend for simplicity
      use_default_backend: true
  criteria:
    - app_id: workload-identity-test-azure