# This Resource Definition creates a Kubernetes service account
# properly annotated for workload identity.
# It requests a Resource of type "azure-managed-identity" via a resource reference
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: wi-azure-k8s-service-account
entity:
  driver_type: humanitec/template
  name: wi-azure-k8s-service-account
  type: k8s-service-account
  driver_inputs:
    values:
      res_id: ${context.res.id}
      azure_managed_identity_client_id: ${resources.azure-managed-identity.outputs.client_id}
      templates:
        init: |
          res_id: {{ .driver.values.res_id }}
          {{- $res_name := .driver.values.res_id | splitList "." | last }}
          name: {{ $res_name | toRawJson }}
          azure_managed_identity_client_id: {{ .driver.values.azure_managed_identity_client_id }}
        manifests: |
          service-account.yaml:
            location: namespace
            data:
              apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: {{ .init.name }}
                annotations:
                  hum-res: {{ .init.res_id }}
                  azure.workload.identity/client-id: {{ .init.azure_managed_identity_client_id }}
        outputs: |
          name: {{ .init.name }}
  # Adjust matching criteria as required
  criteria:
  - app_id: workload-identity-test-azure