apiVersion: config.humanitec.io/v1b1
kind: ScoreDeployConfig
workloads:
  - name: hello-azure-1
    specFile: ./score-1.yaml
    image: mcr.microsoft.com/azure-cli
  - name: hello-azure-2
    specFile: ./score-2.yaml
    image: mcr.microsoft.com/azure-cli
  - name: hello-azure-3
    specFile: ./score-3.yaml
    image: mcr.microsoft.com/azure-cli
