# This Resource Definition of type "aws-policy" provisions
# an identity based IAM policy. It is made to work across Resource Types.
# The resource ARN for the policy as well as the list of actions are passed in
# as variables set in the "params" property in the resource that is co-provisioning it
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: wi-aws-identity-based-iam-policy
entity:
  driver_type: humanitec/opentofu-container-runner-builtin
  name: wi-aws-identity-based-iam-policy
  type: aws-policy
  driver_inputs:
    values:
      variables:
        app_id: "${context.app.id}"
        env_id: "${context.env.id}"
        res_id: "${context.res.id}"
        res_class: "${context.res.class}"
        region: ${resources['config.default#app-config'].outputs.region}
        # The Globally Unique Resource ID (GUResID) is useful for ensuring uniqueness
        guresid: ${context.res.guresid}
      files:
        providers.tf: |
          terraform {
            required_providers {
              aws = {
                source  = "hashicorp/aws"
              }
            }
          }
        variables.tf: |
          variable "app_id" {}
          variable "env_id" {}
          variable "res_id" {}
          variable "res_class" {}
          variable "region" {}
          variable "guresid" {}
          variable "resource_arn" {}
          variable "actions" {
            type = list(string)
          }
        main.tf: |
          # Provider credentials are being injected through environment variables
          # via the EKS workload identity setup
          provider "aws" {
            region = var.region
            default_tags {
              tags = {
                humanitec  = "true"
                hum-app    = var.app_id
                hum-env    = var.env_id
                hum-res    = replace(var.res_id, ".", "-")
                managed-by = "terraform"
              }
            }
          }
          # Prepare the policy document
          data "aws_iam_policy_document" "this" {
            statement {
              # Statement IDs must be alphanumeric
              sid       = replace(var.res_class, "-", "")
              effect    = "Allow"
              # Use the list of actions passed in
              actions   = var.actions
              resources = [
                var.resource_arn
              ]
            }
          }
          # Create the IAM policy
          resource "aws_iam_policy" "policy" {
            name        = var.guresid
            path        = "/"
            description = "IAM Policy $\{var.res_class} for $\{var.resource_arn}"
            policy      = data.aws_iam_policy_document.this.json
          }
        outputs.tf: |
          output "arn" {
            value = aws_iam_policy.policy.arn
          }
      # Using the default TF backend for simplicity
      use_default_backend: true
  # Match the class that is used in the "provision" statement in the Resource Definition of the AWS resource
  criteria:
  - class: sqs-default