# This Resource Definition of type `gcs` implements a "Delegator" resource for the class "read-only"
apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: wi-gcp-gcs-delegator-read-only
entity:
  driver_type: humanitec/echo
  name: wi-gcp-gcs-delegator-read-only
  type: gcs
  driver_inputs:
    values:
      # Referencing the "concrete" Resource and passing through all of its outputs
      name: ${resources['gcs.concrete'].outputs.name}
  provision:
    # Co-provision an IAM Policy resource for this class of gcs
    gcp-iam-policy-binding.gcs-read-only:
      is_dependent: true
  # Adjust matching criteria as required, but must match class "read-only"
  criteria:
  - class: read-only
    app_id: workload-identity-test-gcp