apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: workload-identity-test-gcp-development-3d7877
spec:
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
  serviceAccountName: hello-gcp-1
  containers:
  - name: test-pod
    image: google/cloud-sdk:slim
    command: ["sleep","infinity"]
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
        ephemeral-storage: 10Mi
